// <auto-generated />
using System;
using BookStore.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.DAL.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    [Migration("20260110215942_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStore.Entities.Author", b =>
                {
                    b.Property<int>("AuthorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorID"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.HasKey("AuthorID");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorID = 1,
                            AuthorName = "Nguyễn Nhật Ánh",
                            BirthYear = 1955
                        },
                        new
                        {
                            AuthorID = 2,
                            AuthorName = "J.K. Rowling",
                            BirthYear = 1965
                        },
                        new
                        {
                            AuthorID = 3,
                            AuthorName = "Nam Cao",
                            BirthYear = 1915
                        },
                        new
                        {
                            AuthorID = 4,
                            AuthorName = "Robert C. Martin",
                            BirthYear = 1952
                        },
                        new
                        {
                            AuthorID = 5,
                            AuthorName = "Fujiko F. Fujio",
                            BirthYear = 1933
                        });
                });

            modelBuilder.Entity("BookStore.Entities.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PublisherID")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BookID");

                    b.HasIndex("AuthorID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("PublisherID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            AuthorID = 1,
                            CategoryID = 2,
                            Price = 110000m,
                            PublisherID = 1,
                            Stock = 50,
                            Title = "Mắt Biếc"
                        },
                        new
                        {
                            BookID = 2,
                            AuthorID = 2,
                            CategoryID = 2,
                            Price = 250000m,
                            PublisherID = 1,
                            Stock = 100,
                            Title = "Harry Potter và Hòn Đá Phù Thủy"
                        },
                        new
                        {
                            BookID = 3,
                            AuthorID = 4,
                            CategoryID = 4,
                            Price = 450000m,
                            PublisherID = 4,
                            Stock = 20,
                            Title = "Clean Code (Mã Sạch)"
                        },
                        new
                        {
                            BookID = 4,
                            AuthorID = 5,
                            CategoryID = 5,
                            Price = 25000m,
                            PublisherID = 2,
                            Stock = 200,
                            Title = "Doraemon Tập 1"
                        },
                        new
                        {
                            BookID = 5,
                            AuthorID = 3,
                            CategoryID = 1,
                            Price = 15000m,
                            PublisherID = 3,
                            Stock = 500,
                            Title = "Tiếng Việt Lớp 1"
                        });
                });

            modelBuilder.Entity("BookStore.Entities.BookCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryID");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Sách Giáo Khoa"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Tiểu Thuyết & Văn Học"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Kinh Tế & Quản Trị"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Công Nghệ Thông Tin"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Truyện Tranh (Manga)"
                        });
                });

            modelBuilder.Entity("BookStore.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            Address = "N/A",
                            FullName = "Khách Vãng Lai",
                            Phone = "0000000000"
                        },
                        new
                        {
                            CustomerID = 2,
                            Address = "Hà Nội",
                            FullName = "Trần Văn A",
                            Phone = "0909123456"
                        },
                        new
                        {
                            CustomerID = 3,
                            Address = "Đà Nẵng",
                            FullName = "Lê Thị B",
                            Phone = "0918123456"
                        });
                });

            modelBuilder.Entity("BookStore.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("InvoiceID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("UserID");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceID = 1,
                            CustomerID = 2,
                            Date = new DateTime(2026, 1, 10, 4, 59, 42, 437, DateTimeKind.Local).AddTicks(119),
                            TotalAmount = 160000m,
                            UserID = 2
                        });
                });

            modelBuilder.Entity("BookStore.Entities.InvoiceDetail", b =>
                {
                    b.Property<int>("DetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailID"));

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int>("InvoiceID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DetailID");

                    b.HasIndex("BookID");

                    b.HasIndex("InvoiceID");

                    b.ToTable("InvoiceDetails");

                    b.HasData(
                        new
                        {
                            DetailID = 1,
                            BookID = 1,
                            InvoiceID = 1,
                            Quantity = 1,
                            UnitPrice = 110000m
                        },
                        new
                        {
                            DetailID = 2,
                            BookID = 4,
                            InvoiceID = 1,
                            Quantity = 2,
                            UnitPrice = 25000m
                        });
                });

            modelBuilder.Entity("BookStore.Entities.Publisher", b =>
                {
                    b.Property<int>("PublisherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PublisherID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PublisherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PublisherID");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            PublisherID = 1,
                            Address = "161B Lý Chính Thắng, TP.HCM",
                            PublisherName = "NXB Trẻ"
                        },
                        new
                        {
                            PublisherID = 2,
                            Address = "55 Quang Trung, Hà Nội",
                            PublisherName = "NXB Kim Đồng"
                        },
                        new
                        {
                            PublisherID = 3,
                            Address = "81 Trần Hưng Đạo, Hà Nội",
                            PublisherName = "NXB Giáo Dục"
                        },
                        new
                        {
                            PublisherID = 4,
                            Address = "USA",
                            PublisherName = "O'Reilly Media"
                        });
                });

            modelBuilder.Entity("BookStore.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            RoleName = "Staff"
                        });
                });

            modelBuilder.Entity("BookStore.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            FullName = "Administrator",
                            IsActive = true,
                            Password = "123",
                            RoleID = 1,
                            UserName = "admin"
                        },
                        new
                        {
                            UserID = 2,
                            FullName = "Nhân viên Bán hàng A",
                            IsActive = true,
                            Password = "123",
                            RoleID = 2,
                            UserName = "staff"
                        });
                });

            modelBuilder.Entity("BookStore.Entities.Book", b =>
                {
                    b.HasOne("BookStore.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookStore.Entities.BookCategory", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Entities.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("BookStore.Entities.Invoice", b =>
                {
                    b.HasOne("BookStore.Entities.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookStore.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookStore.Entities.InvoiceDetail", b =>
                {
                    b.HasOne("BookStore.Entities.Book", "Book")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("BookStore.Entities.User", b =>
                {
                    b.HasOne("BookStore.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BookStore.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookStore.Entities.Book", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("BookStore.Entities.BookCategory", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookStore.Entities.Customer", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("BookStore.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("BookStore.Entities.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookStore.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
